/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyWiseKitRouteImport } from './routes/company-wise-kit'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as ExploreSheetsRouteImport } from './routes/explore-sheets'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MySheetsRouteImport } from './routes/my-sheets'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyWiseKitRoute = CompanyWiseKitRouteImport.update({
  id: '/company-wise-kit',
  path: '/company-wise-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSheetsRoute = ExploreSheetsRouteImport.update({
  id: '/explore-sheets',
  path: '/explore-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MySheetsRoute = MySheetsRouteImport.update({
  id: '/my-sheets',
  path: '/my-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company-wise-kit': typeof CompanyWiseKitRoute
  '/contests': typeof ContestsRoute
  '/explore-sheets': typeof ExploreSheetsRoute
  '/feedback': typeof FeedbackRoute
  '/help-center': typeof HelpCenterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-sheets': typeof MySheetsRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company-wise-kit': typeof CompanyWiseKitRoute
  '/contests': typeof ContestsRoute
  '/explore-sheets': typeof ExploreSheetsRoute
  '/feedback': typeof FeedbackRoute
  '/help-center': typeof HelpCenterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-sheets': typeof MySheetsRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company-wise-kit': typeof CompanyWiseKitRoute
  '/contests': typeof ContestsRoute
  '/explore-sheets': typeof ExploreSheetsRoute
  '/feedback': typeof FeedbackRoute
  '/help-center': typeof HelpCenterRoute
  '/leaderboard': typeof LeaderboardRoute
  '/my-sheets': typeof MySheetsRoute
  '/notes': typeof NotesRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company-wise-kit'
    | '/contests'
    | '/explore-sheets'
    | '/feedback'
    | '/help-center'
    | '/leaderboard'
    | '/my-sheets'
    | '/notes'
    | '/portfolio'
    | '/settings'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company-wise-kit'
    | '/contests'
    | '/explore-sheets'
    | '/feedback'
    | '/help-center'
    | '/leaderboard'
    | '/my-sheets'
    | '/notes'
    | '/portfolio'
    | '/settings'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/company-wise-kit'
    | '/contests'
    | '/explore-sheets'
    | '/feedback'
    | '/help-center'
    | '/leaderboard'
    | '/my-sheets'
    | '/notes'
    | '/portfolio'
    | '/settings'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyWiseKitRoute: typeof CompanyWiseKitRoute
  ContestsRoute: typeof ContestsRoute
  ExploreSheetsRoute: typeof ExploreSheetsRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpCenterRoute: typeof HelpCenterRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MySheetsRoute: typeof MySheetsRoute
  NotesRoute: typeof NotesRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-wise-kit': {
      id: '/company-wise-kit'
      path: '/company-wise-kit'
      fullPath: '/company-wise-kit'
      preLoaderRoute: typeof CompanyWiseKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-sheets': {
      id: '/explore-sheets'
      path: '/explore-sheets'
      fullPath: '/explore-sheets'
      preLoaderRoute: typeof ExploreSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sheets': {
      id: '/my-sheets'
      path: '/my-sheets'
      fullPath: '/my-sheets'
      preLoaderRoute: typeof MySheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyWiseKitRoute: CompanyWiseKitRoute,
  ContestsRoute: ContestsRoute,
  ExploreSheetsRoute: ExploreSheetsRoute,
  FeedbackRoute: FeedbackRoute,
  HelpCenterRoute: HelpCenterRoute,
  LeaderboardRoute: LeaderboardRoute,
  MySheetsRoute: MySheetsRoute,
  NotesRoute: NotesRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
